language: python

matrix:
  include:
    - os: linux
      env: PYTHON=3.6
    - os: linux
      env: PYTHON=3.7
    - os: linux
      env: PYTHON=3.8
    - os: osx
      env: PYTHON=3.7

branches:
  only:
    - master

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt update;
      sudo apt install -y libeigen3-dev;
      sudo cp -r /usr/include/eigen3 /usr/local/include/eigen3;
      pip install pybind11;
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install -y eigen3;
      pip install pybind11;
    fi

install:
  - python3 setup.py install

script:
  - pytest