language: python

dist: trusty

matrix:
  include:
    - os: linux
      env: PYTHON=3.6
    - os: linux
      env: PYTHON=3.7
    - os: linux
      env: PYTHON=3.8

branches:
  only:
    - master

before_install:
  - sudo apt update
  - sudo apt install -y libeigen3-dev
  # Linux和macOS的默认安装路径有差异.
  - sudo cp -r /usr/include/eigen3 /usr/local/include/eigen3
  - pip install pybind11

install:
  - python3 setup.py install

script:
  - pytest