name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matirx:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Before install
        run: |
          sudo apt update;
          sudo apt install -y libeigen3-dev;
          sudo cp -r /usr/include/eigen3 /usr/local/include/eigen3;
          pip install pybind11;
          pip install scikit-learn==0.23.2;

      - name: Test with pytest
        run: |
          - pytest
